### ISSUE TITLE
Teamcity agent name is not updating with dynamic container name.

### ISSUE THREAD

**Issue by nchidipothu** [JeanRev/TeamcityDockerCloudPlugin#34] opened 2017-11-02 03:18 UTC
Hi,

When we create multiple container with one docker image, all multiple containers having different agent names( as agent name having dynamic container name) but recently we have lost that one.

Please find the attached screen shot.
![2017_11_01_14_51_46_infobright_projects_builds_and_deployments_rc_builds_build_centos7_pack](https://user-images.githubusercontent.com/23451854/32308154-655bec90-bfaa-11e7-9760-a83fc48afc12.png)
 

Can you please help with this.

Thanks,
Naresh Ch

**Comment by nchidipothu** [comment] 2017-11-02 03:21
Hi,

For reported docker image, we don't have any special configuration. it have docker image and some environment properties.

Thanks,

**Comment by JeanRev** [comment] 2017-11-02 06:10
Hi Naresh,

Agent name are registration is performed using a special extension of the TeamCity server. The generated name will be composed of the container name as reported by Docker, as well as the agent host address as reported by TeamCity. In your situation, it seems that only the agent host address is displayed (this is the default for non-cloud agents if you did not specify a static name in the agent properties file). A possible explanation would be that the started agent is not recognized as a cloud agent by the plugin.

If you click on the agent name in the list of build jobs, is the agent reported as being part of your defined cloud profile ?
![screenshot_20171102_070254](https://user-images.githubusercontent.com/8666989/32312114-3f4604ae-bf9c-11e7-9201-6d8aa476ca2b.png)

Are you currently working with multiple Docker daemons ? (if yes then it would be possible for two containers to have the same name, which could result in an agent name collision. The TeamCity server is however expected to handle this case gracefully and add an unique id at the end of the agent name).

**Comment by nchidipothu** [comment] 2017-11-05 07:51
Hi,

We are using only one docker daemons for linux,

Please find the attached screenshot.

<img width="751" alt="screen shot 2017-11-05 at 1 20 27 pm" src="https://user-images.githubusercontent.com/23451854/32412954-264d826e-c22c-11e7-9c00-501d73c21689.png">

**Comment by JeanRev** [comment] 2017-11-08 05:46
Thank for you for the info. According to its description your cloud image looks fine. Right now, I don't seem to be able to reproduce the issue.

Can you provide me the logs/teamcity-clouds.log file of your teamcity installation?

**Comment by nchidipothu** [comment] 2017-11-12 15:30
[teamcity-clouds.log](https://github.com/JeanRev/TeamcityDockerCloudPlugin/files/1464807/teamcity-clouds.log)
Hi,

I have attached required files.
<img width="1135" alt="screen shot 2017-11-12 at 8 53 10 pm" src="https://user-images.githubusercontent.com/23451854/32700521-6a2e29d2-c7ec-11e7-8083-3774fa476de9.png">
<img width="534" alt="screen shot 2017-11-12 at 8 54 20 pm" src="https://user-images.githubusercontent.com/23451854/32700522-6a5866a2-c7ec-11e7-86d6-2c5a65119278.png">
<img width="537" alt="screen shot 2017-11-12 at 8 54 34 pm" src="https://user-images.githubusercontent.com/23451854/32700523-6a83b3ca-c7ec-11e7-9798-33197ffd2fe1.png">
<img width="849" alt="screen shot 2017-11-12 at 8 56 33 pm" src="https://user-images.githubusercontent.com/23451854/32700524-6aaf4a6c-c7ec-11e7-9f54-0e880a2d76af.png">

**Comment by nchidipothu** [comment] 2017-11-19 17:02
Hi,

Any update at this ?

**Comment by JeanRev** [comment] 2017-11-19 19:31
Hi,

Sorry for the delay. I took a look to the log files and tried to reproduce the issue but without success so far.

It looks like that the TeamCity server is sometimes not invoking our agent name provider, but the exact cause is not clear.

Does it happens often?

**Comment by nchidipothu** [comment] 2017-11-23 03:41
Hi,

This behaviour only with some of docker images.

**Comment by JeanRev** [comment] 2017-11-23 05:51
Thank you for the precision. Could you inspect the image (using ```docker inspect```) and send me the output? (you can attach it here or send it by email at this address: revertera AT puzzle.ch)

**Comment by JeanRev** [comment] 2017-12-14 05:47
According to our mail exchanges communication, it appeared that the agent name where externally set using the AGENT_NAME environment variable defined in the container properties.

This setup currently can't be supported, and is also not expected to work with other kind of cloud profiles. Forcing a specific agent name on a cloud image will makes every started agent from that image to bear the same name, and duplicates agent names is not allowed by the TeamCity server.

I'll close the issue for now, but feel free to reopen it if required.

**Closed as completed by JeanRev** 2017-12-14 05:47 UTC
Labels: wontfix
